#setup server port
server:
  port: 8080

#setup local h2 database config
spring:
  datasource:
    url: jdbc:h2:file:./h2data/todoapp
    driver-class-name: org.h2.Driver
    username: admin
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop

#setup local h2 console
  h2:
    console:
      path: /h2-console
      enabled: true
      settings:
        web-allow-others: false

#setup devtools restart support
  devtools:
    restart:
      additional-exclude: true
  application:
    name: TodoListApplication

#setup logging level
logging:
  level:
    root: INFO
    pl.rstepniewski.todolistapp.controllers: DEBUG
# Log file configuration
  file:
    name: logs/todoapp_log.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
